/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_absval.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_add.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_addsub.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_ash.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_binenc.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_bsh.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_cmp2.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_cmp6.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_csa.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_dec.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_decode.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_mux_any.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_prienc.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_satrnd.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW01_sub.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_mac.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_mult.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_mult_2_stage.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_mult_3_stage.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_mult_4_stage.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_mult_5_stage.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_mult_6_stage.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_mult_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_multp.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_prod_sum.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_prod_sum1.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_sum.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW02_tree.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_bictr_dcnto.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_bictr_decode.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_bictr_scnto.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_lfsr_dcnto.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_lfsr_load.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_lfsr_scnto.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_lfsr_updn.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_pipe_reg.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_reg_s_pl.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_shftreg.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW03_updn_ctr.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW04_par_gen.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW04_shad_reg.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_8b10b_dec.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_8b10b_enc.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_8b10b_unbal.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_FP_ALIGN.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_Z_control_force.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_addsub_dx.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_arb_2t.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_arb_dp.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_arb_fcfs.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_arb_rr.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_arb_sp.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_asymdata_inbuf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_asymdata_outbuf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_asymfifo_s1_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_asymfifo_s1_sf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_asymfifo_s2_sf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_asymfifoctl_2c_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_asymfifoctl_s1_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_asymfifoctl_s1_sf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_asymfifoctl_s2_sf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_bc_1.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_bc_10.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_bc_2.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_bc_3.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_bc_4.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_bc_5.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_bc_7.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_bc_8.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_bc_9.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_bin2gray.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_cmp_dx.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_cntr_gray.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_control_force.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_crc_p.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_crc_s.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_data_qsync_hl.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_data_qsync_lh.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_data_sync.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_data_sync_1c.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_data_sync_na.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_dct_2d.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_decode_en.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_div.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_div_pipe.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_div_sat.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_div_seq.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_dpll_sd.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ecc.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_exp2.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fifo_2c_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fifo_s1_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fifo_s1_sf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fifo_s2_sf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fifoctl_2c_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fifoctl_s1_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fifoctl_s1_sf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fifoctl_s2_sf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fifoctl_s2dr_sf.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fir.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fir_seq.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_add.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_add_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_addsub.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_addsub_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_cmp.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_cmp_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_div.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_div_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_div_seq.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_dp2.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_dp3.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_dp4.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_exp.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_exp2.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_flt2i.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_i2flt.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_ifp_conv.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_invsqrt.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_ln.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_log2.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_mac.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_mac_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_mult.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_mult_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_recip.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_recip_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_sqrt.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_square.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_sub.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_sub_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_sum3.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_sum3_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_fp_sum4.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_gray2bin.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_gray_sync.v
//usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ifp_addsub.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ifp_fp_conv.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ifp_mult.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_iir_dc.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_iir_sc.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_inv_sqrt.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lbsh.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ln.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lod.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_log2.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_cntr_up_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_cntr_updn_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_fifo_1c_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_fifoctl_1c_df.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_fp_multifunc.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_fp_multifunc_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_multifunc.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_multifunc_DG.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_pipe_mgr.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_piped_div.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_piped_ecc.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_piped_fp_add.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_piped_fp_div.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_piped_fp_mult.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_piped_fp_recip.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_piped_fp_sum3.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_piped_mult.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_piped_prod_sum.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lp_piped_sqrt.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lsd.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lza.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_lzd.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_minmax.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_mult_dx.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_mult_pipe.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_mult_seq.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_norm.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_norm_rnd.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_observ_dgen.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_piped_mac.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_pl_reg.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_pricod.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_prod_sum_pipe.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_pulse_sync.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_pulseack_sync.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_2r_2w_s_dff.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_2r_w_a_dff.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_2r_w_a_lat.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_2r_w_s_dff.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_2r_w_s_lat.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_r_w_2c_dff.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_r_w_a_dff.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_r_w_a_lat.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_r_w_s_dff.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_r_w_s_lat.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_rw_a_dff.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_rw_a_lat.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_rw_s_dff.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_ram_rw_s_lat.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_rash.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_rbsh.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_reset_sync.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_shifter.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_sincos.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_sla.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_sqrt.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_sqrt_pipe.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_sqrt_rem.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_sqrt_seq.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_square.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_squarep.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_sra.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_stack.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_stackctl.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_stream_sync.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_sync.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_tap.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_tap_uc.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_thermdec.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_wc_d1_s.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DW_wc_s1_s.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/DWsc_sync.v
/usr/cad/synopsys/synthesis/cur/dw/sim_ver/vcs
