###################################################################

# Created by write_sdc on Sun Nov 12 16:03:33 2023

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name enG30K -library fsa0m_a_generic_core_ss1p62v125c
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {rand_num[31]}]
set_load -pin_load 0.05 [get_ports {rand_num[30]}]
set_load -pin_load 0.05 [get_ports {rand_num[29]}]
set_load -pin_load 0.05 [get_ports {rand_num[28]}]
set_load -pin_load 0.05 [get_ports {rand_num[27]}]
set_load -pin_load 0.05 [get_ports {rand_num[26]}]
set_load -pin_load 0.05 [get_ports {rand_num[25]}]
set_load -pin_load 0.05 [get_ports {rand_num[24]}]
set_load -pin_load 0.05 [get_ports {rand_num[23]}]
set_load -pin_load 0.05 [get_ports {rand_num[22]}]
set_load -pin_load 0.05 [get_ports {rand_num[21]}]
set_load -pin_load 0.05 [get_ports {rand_num[20]}]
set_load -pin_load 0.05 [get_ports {rand_num[19]}]
set_load -pin_load 0.05 [get_ports {rand_num[18]}]
set_load -pin_load 0.05 [get_ports {rand_num[17]}]
set_load -pin_load 0.05 [get_ports {rand_num[16]}]
set_load -pin_load 0.05 [get_ports {rand_num[15]}]
set_load -pin_load 0.05 [get_ports {rand_num[14]}]
set_load -pin_load 0.05 [get_ports {rand_num[13]}]
set_load -pin_load 0.05 [get_ports {rand_num[12]}]
set_load -pin_load 0.05 [get_ports {rand_num[11]}]
set_load -pin_load 0.05 [get_ports {rand_num[10]}]
set_load -pin_load 0.05 [get_ports {rand_num[9]}]
set_load -pin_load 0.05 [get_ports {rand_num[8]}]
set_load -pin_load 0.05 [get_ports {rand_num[7]}]
set_load -pin_load 0.05 [get_ports {rand_num[6]}]
set_load -pin_load 0.05 [get_ports {rand_num[5]}]
set_load -pin_load 0.05 [get_ports {rand_num[4]}]
set_load -pin_load 0.05 [get_ports {rand_num[3]}]
set_load -pin_load 0.05 [get_ports {rand_num[2]}]
set_load -pin_load 0.05 [get_ports {rand_num[1]}]
set_load -pin_load 0.05 [get_ports {rand_num[0]}]
set_max_capacitance 0.15 [get_ports clk1]
set_max_capacitance 0.15 [get_ports clk2]
set_max_capacitance 0.15 [get_ports clk3]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports in_valid]
set_max_capacitance 0.15 [get_ports {seed[31]}]
set_max_capacitance 0.15 [get_ports {seed[30]}]
set_max_capacitance 0.15 [get_ports {seed[29]}]
set_max_capacitance 0.15 [get_ports {seed[28]}]
set_max_capacitance 0.15 [get_ports {seed[27]}]
set_max_capacitance 0.15 [get_ports {seed[26]}]
set_max_capacitance 0.15 [get_ports {seed[25]}]
set_max_capacitance 0.15 [get_ports {seed[24]}]
set_max_capacitance 0.15 [get_ports {seed[23]}]
set_max_capacitance 0.15 [get_ports {seed[22]}]
set_max_capacitance 0.15 [get_ports {seed[21]}]
set_max_capacitance 0.15 [get_ports {seed[20]}]
set_max_capacitance 0.15 [get_ports {seed[19]}]
set_max_capacitance 0.15 [get_ports {seed[18]}]
set_max_capacitance 0.15 [get_ports {seed[17]}]
set_max_capacitance 0.15 [get_ports {seed[16]}]
set_max_capacitance 0.15 [get_ports {seed[15]}]
set_max_capacitance 0.15 [get_ports {seed[14]}]
set_max_capacitance 0.15 [get_ports {seed[13]}]
set_max_capacitance 0.15 [get_ports {seed[12]}]
set_max_capacitance 0.15 [get_ports {seed[11]}]
set_max_capacitance 0.15 [get_ports {seed[10]}]
set_max_capacitance 0.15 [get_ports {seed[9]}]
set_max_capacitance 0.15 [get_ports {seed[8]}]
set_max_capacitance 0.15 [get_ports {seed[7]}]
set_max_capacitance 0.15 [get_ports {seed[6]}]
set_max_capacitance 0.15 [get_ports {seed[5]}]
set_max_capacitance 0.15 [get_ports {seed[4]}]
set_max_capacitance 0.15 [get_ports {seed[3]}]
set_max_capacitance 0.15 [get_ports {seed[2]}]
set_max_capacitance 0.15 [get_ports {seed[1]}]
set_max_capacitance 0.15 [get_ports {seed[0]}]
set_max_fanout 10 [get_ports clk1]
set_max_fanout 10 [get_ports clk2]
set_max_fanout 10 [get_ports clk3]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports in_valid]
set_max_fanout 10 [get_ports {seed[31]}]
set_max_fanout 10 [get_ports {seed[30]}]
set_max_fanout 10 [get_ports {seed[29]}]
set_max_fanout 10 [get_ports {seed[28]}]
set_max_fanout 10 [get_ports {seed[27]}]
set_max_fanout 10 [get_ports {seed[26]}]
set_max_fanout 10 [get_ports {seed[25]}]
set_max_fanout 10 [get_ports {seed[24]}]
set_max_fanout 10 [get_ports {seed[23]}]
set_max_fanout 10 [get_ports {seed[22]}]
set_max_fanout 10 [get_ports {seed[21]}]
set_max_fanout 10 [get_ports {seed[20]}]
set_max_fanout 10 [get_ports {seed[19]}]
set_max_fanout 10 [get_ports {seed[18]}]
set_max_fanout 10 [get_ports {seed[17]}]
set_max_fanout 10 [get_ports {seed[16]}]
set_max_fanout 10 [get_ports {seed[15]}]
set_max_fanout 10 [get_ports {seed[14]}]
set_max_fanout 10 [get_ports {seed[13]}]
set_max_fanout 10 [get_ports {seed[12]}]
set_max_fanout 10 [get_ports {seed[11]}]
set_max_fanout 10 [get_ports {seed[10]}]
set_max_fanout 10 [get_ports {seed[9]}]
set_max_fanout 10 [get_ports {seed[8]}]
set_max_fanout 10 [get_ports {seed[7]}]
set_max_fanout 10 [get_ports {seed[6]}]
set_max_fanout 10 [get_ports {seed[5]}]
set_max_fanout 10 [get_ports {seed[4]}]
set_max_fanout 10 [get_ports {seed[3]}]
set_max_fanout 10 [get_ports {seed[2]}]
set_max_fanout 10 [get_ports {seed[1]}]
set_max_fanout 10 [get_ports {seed[0]}]
set_max_transition 3 [get_ports clk1]
set_max_transition 3 [get_ports clk2]
set_max_transition 3 [get_ports clk3]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports in_valid]
set_max_transition 3 [get_ports {seed[31]}]
set_max_transition 3 [get_ports {seed[30]}]
set_max_transition 3 [get_ports {seed[29]}]
set_max_transition 3 [get_ports {seed[28]}]
set_max_transition 3 [get_ports {seed[27]}]
set_max_transition 3 [get_ports {seed[26]}]
set_max_transition 3 [get_ports {seed[25]}]
set_max_transition 3 [get_ports {seed[24]}]
set_max_transition 3 [get_ports {seed[23]}]
set_max_transition 3 [get_ports {seed[22]}]
set_max_transition 3 [get_ports {seed[21]}]
set_max_transition 3 [get_ports {seed[20]}]
set_max_transition 3 [get_ports {seed[19]}]
set_max_transition 3 [get_ports {seed[18]}]
set_max_transition 3 [get_ports {seed[17]}]
set_max_transition 3 [get_ports {seed[16]}]
set_max_transition 3 [get_ports {seed[15]}]
set_max_transition 3 [get_ports {seed[14]}]
set_max_transition 3 [get_ports {seed[13]}]
set_max_transition 3 [get_ports {seed[12]}]
set_max_transition 3 [get_ports {seed[11]}]
set_max_transition 3 [get_ports {seed[10]}]
set_max_transition 3 [get_ports {seed[9]}]
set_max_transition 3 [get_ports {seed[8]}]
set_max_transition 3 [get_ports {seed[7]}]
set_max_transition 3 [get_ports {seed[6]}]
set_max_transition 3 [get_ports {seed[5]}]
set_max_transition 3 [get_ports {seed[4]}]
set_max_transition 3 [get_ports {seed[3]}]
set_max_transition 3 [get_ports {seed[2]}]
set_max_transition 3 [get_ports {seed[1]}]
set_max_transition 3 [get_ports {seed[0]}]
create_clock [get_ports clk1]  -period 14.1  -waveform {0 7.05}
set_clock_uncertainty 0.1  [get_clocks clk1]
set_clock_transition -max -rise 0.1 [get_clocks clk1]
set_clock_transition -max -fall 0.1 [get_clocks clk1]
set_clock_transition -min -rise 0.1 [get_clocks clk1]
set_clock_transition -min -fall 0.1 [get_clocks clk1]
create_clock [get_ports clk2]  -period 3.9  -waveform {0 1.95}
set_clock_uncertainty 0.1  [get_clocks clk2]
set_clock_transition -max -rise 0.1 [get_clocks clk2]
set_clock_transition -max -fall 0.1 [get_clocks clk2]
set_clock_transition -min -rise 0.1 [get_clocks clk2]
set_clock_transition -min -fall 0.1 [get_clocks clk2]
create_clock [get_ports clk3]  -period 20.7  -waveform {0 10.35}
set_clock_uncertainty 0.1  [get_clocks clk3]
set_clock_transition -max -rise 0.1 [get_clocks clk3]
set_clock_transition -max -fall 0.1 [get_clocks clk3]
set_clock_transition -min -rise 0.1 [get_clocks clk3]
set_clock_transition -min -fall 0.1 [get_clocks clk3]
set_input_delay -clock clk1  0  [get_ports clk1]
set_input_delay -clock clk2  0  [get_ports clk2]
set_input_delay -clock clk3  0  [get_ports clk3]
set_input_delay -clock clk1  0  [get_ports rst_n]
set_input_delay -clock clk1  -max 7.05  [get_ports in_valid]
set_input_delay -clock clk1  -min 0  [get_ports in_valid]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[31]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[31]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[30]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[30]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[29]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[29]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[28]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[28]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[27]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[27]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[26]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[26]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[25]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[25]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[24]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[24]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[23]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[23]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[22]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[22]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[21]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[21]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[20]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[20]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[19]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[19]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[18]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[18]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[17]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[17]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[16]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[16]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[15]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[15]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[14]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[14]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[13]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[13]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[12]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[12]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[11]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[11]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[10]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[10]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[9]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[9]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[8]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[8]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[7]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[7]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[6]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[6]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[5]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[5]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[4]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[4]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[3]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[3]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[2]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[2]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[1]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[1]}]
set_input_delay -clock clk1  -max 7.05  [get_ports {seed[0]}]
set_input_delay -clock clk1  -min 0  [get_ports {seed[0]}]
set_output_delay -clock clk3  -max 10.35  [get_ports out_valid]
set_output_delay -clock clk3  -min 0  [get_ports out_valid]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[31]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[31]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[30]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[30]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[29]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[29]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[28]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[28]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[27]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[27]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[26]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[26]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[25]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[25]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[24]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[24]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[23]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[23]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[22]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[22]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[21]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[21]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[20]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[20]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[19]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[19]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[18]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[18]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[17]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[17]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[16]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[16]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[15]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[15]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[14]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[14]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[13]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[13]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[12]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[12]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[11]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[11]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[10]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[10]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[9]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[9]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[8]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[8]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[7]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[7]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[6]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[6]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[5]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[5]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[4]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[4]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[3]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[3]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[2]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[2]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[1]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[1]}]
set_output_delay -clock clk3  -max 10.35  [get_ports {rand_num[0]}]
set_output_delay -clock clk3  -min 0  [get_ports {rand_num[0]}]
set_clock_groups  -asynchronous -name group1  -group [get_clocks clk1] -group  \
[get_clocks clk2] -group [get_clocks clk3]
set_input_transition -max 0.5  [get_ports clk1]
set_input_transition -min 0.5  [get_ports clk1]
set_input_transition -max 0.5  [get_ports clk2]
set_input_transition -min 0.5  [get_ports clk2]
set_input_transition -max 0.5  [get_ports clk3]
set_input_transition -min 0.5  [get_ports clk3]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports in_valid]
set_input_transition -min 0.5  [get_ports in_valid]
set_input_transition -max 0.5  [get_ports {seed[31]}]
set_input_transition -min 0.5  [get_ports {seed[31]}]
set_input_transition -max 0.5  [get_ports {seed[30]}]
set_input_transition -min 0.5  [get_ports {seed[30]}]
set_input_transition -max 0.5  [get_ports {seed[29]}]
set_input_transition -min 0.5  [get_ports {seed[29]}]
set_input_transition -max 0.5  [get_ports {seed[28]}]
set_input_transition -min 0.5  [get_ports {seed[28]}]
set_input_transition -max 0.5  [get_ports {seed[27]}]
set_input_transition -min 0.5  [get_ports {seed[27]}]
set_input_transition -max 0.5  [get_ports {seed[26]}]
set_input_transition -min 0.5  [get_ports {seed[26]}]
set_input_transition -max 0.5  [get_ports {seed[25]}]
set_input_transition -min 0.5  [get_ports {seed[25]}]
set_input_transition -max 0.5  [get_ports {seed[24]}]
set_input_transition -min 0.5  [get_ports {seed[24]}]
set_input_transition -max 0.5  [get_ports {seed[23]}]
set_input_transition -min 0.5  [get_ports {seed[23]}]
set_input_transition -max 0.5  [get_ports {seed[22]}]
set_input_transition -min 0.5  [get_ports {seed[22]}]
set_input_transition -max 0.5  [get_ports {seed[21]}]
set_input_transition -min 0.5  [get_ports {seed[21]}]
set_input_transition -max 0.5  [get_ports {seed[20]}]
set_input_transition -min 0.5  [get_ports {seed[20]}]
set_input_transition -max 0.5  [get_ports {seed[19]}]
set_input_transition -min 0.5  [get_ports {seed[19]}]
set_input_transition -max 0.5  [get_ports {seed[18]}]
set_input_transition -min 0.5  [get_ports {seed[18]}]
set_input_transition -max 0.5  [get_ports {seed[17]}]
set_input_transition -min 0.5  [get_ports {seed[17]}]
set_input_transition -max 0.5  [get_ports {seed[16]}]
set_input_transition -min 0.5  [get_ports {seed[16]}]
set_input_transition -max 0.5  [get_ports {seed[15]}]
set_input_transition -min 0.5  [get_ports {seed[15]}]
set_input_transition -max 0.5  [get_ports {seed[14]}]
set_input_transition -min 0.5  [get_ports {seed[14]}]
set_input_transition -max 0.5  [get_ports {seed[13]}]
set_input_transition -min 0.5  [get_ports {seed[13]}]
set_input_transition -max 0.5  [get_ports {seed[12]}]
set_input_transition -min 0.5  [get_ports {seed[12]}]
set_input_transition -max 0.5  [get_ports {seed[11]}]
set_input_transition -min 0.5  [get_ports {seed[11]}]
set_input_transition -max 0.5  [get_ports {seed[10]}]
set_input_transition -min 0.5  [get_ports {seed[10]}]
set_input_transition -max 0.5  [get_ports {seed[9]}]
set_input_transition -min 0.5  [get_ports {seed[9]}]
set_input_transition -max 0.5  [get_ports {seed[8]}]
set_input_transition -min 0.5  [get_ports {seed[8]}]
set_input_transition -max 0.5  [get_ports {seed[7]}]
set_input_transition -min 0.5  [get_ports {seed[7]}]
set_input_transition -max 0.5  [get_ports {seed[6]}]
set_input_transition -min 0.5  [get_ports {seed[6]}]
set_input_transition -max 0.5  [get_ports {seed[5]}]
set_input_transition -min 0.5  [get_ports {seed[5]}]
set_input_transition -max 0.5  [get_ports {seed[4]}]
set_input_transition -min 0.5  [get_ports {seed[4]}]
set_input_transition -max 0.5  [get_ports {seed[3]}]
set_input_transition -min 0.5  [get_ports {seed[3]}]
set_input_transition -max 0.5  [get_ports {seed[2]}]
set_input_transition -min 0.5  [get_ports {seed[2]}]
set_input_transition -max 0.5  [get_ports {seed[1]}]
set_input_transition -min 0.5  [get_ports {seed[1]}]
set_input_transition -max 0.5  [get_ports {seed[0]}]
set_input_transition -min 0.5  [get_ports {seed[0]}]
